services:
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
    # port for other docker containers
      - "9092:9092"
      # ports for external connections (python script )
      - "19092:19092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=localhost
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
  
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    ports:
      - "8081:8081"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
    volumes:
      - ./ingestion/:/app/ingestion
      - ./pipeline/:/app/pipeline
      - ./data/:/app/data
  
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-worker
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    volumes:
      - ./ingestion/:/app/ingestion
      - ./pipeline/:/app/pipeline
      - ./data/:/app/data

  bronze-ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bronze-ingestion
    depends_on:
      - spark-worker
      - kafka
    volumes:
      - ./ingestion/:/app/ingestion
      - ./pipeline/:/app/pipeline
      - ./data/:/app/data
    command: spark-submit --master spark://spark-master:7077 scripts/bronze_ingestion.py
  

networks:
  default:
    driver: bridge
  # silver-schema